server:
  port: 8084

spring:
  devtools:
    livereload:
      enabled: true
      # thymeleaf cache ????
  thymeleaf:
    cache : false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
  h2:
    console:
      enabled: true
      # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      #path: /h2-console  # H2 Console? Path
  datasource:
    driver-class-name: org.h2.Driver  # Database? H2? ?????.
    url: jdbc:h2:tcp://localhost/~/test  # H2 ?? ??
    username: sa  # H2 ?? ? ??? username ?? (??? ??? ??)
    password:  # H2 ?? ? ??? password ?? (??? ??? ??)

  ## JPA Setting Info
  jpa:
    hibernate:
      ddl-auto: create-drop  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        diarect: org.hibernate.dialect.H2Dialect  # ??? ??? ?? ?????? ??? ?????.
        #show_sql: true  # sql ??? ?????.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql ??? ????? ?????.

# ?? ?? ??
logging:
  level:
    # hibernate ? ??? ?? ??? debug??? ??
    # jpa hibernate? ???? sql? ??? ??? ???? ?? ??
    org:
      hibernate:
        SQL: WARN
        type: WARN # ?? ???? ????? ???? ??


